### ISSUE TITLE
Documentable uses the default template instead of the template that's in the current directory.

### ISSUE THREAD

**Issue by JJ** [Raku/Documentable#102]
With the last changes, the behavior of the command we used to generate documentation has changed; it now takes a different template, with this result
![Captura de pantalla de 2020-07-02 18-22-28](https://user-images.githubusercontent.com/500/86386617-4f4e4c80-bc92-11ea-8887-6d9ea572f10f.png)
All documentation-specific CSS and JS have disappeared, leaving the plain documentation.
Documentable shouldn't change behavior from one release to the next; it should really make sure that it does not break its most important client, documentation. Maybe one test should be added for this, probably as a GitHub action or similar.

**Comment by antoniogamiz** [comment]
Due to
