### ISSUE TITLE
Error in the (apparently) default HTML template

### ISSUE THREAD

**Issue by JJ** [Raku/Documentable#110]
**Describe the bug**

When the documentation is generated with the default template, this HTML error (apparently a non-closed tag) appears

**Screenshots**
![Captura de pantalla de 2020-07-16 12-43-50](https://user-images.githubusercontent.com/500/87662218-28981780-c762-11ea-8a55-fcb6941eaf5a.png)

Raku version is 2020.06, documentable version 1.3.1

**Comment by antoniogamiz** [comment]
I have added a message to see what template is being used. The template used in that case looks incomplete, so I think is not using the latest one.

Anyway,  while looking into this I have found two errors in the template:

- Index page has a submenu:
![image](https://user-images.githubusercontent.com/22995015/87851290-a6d9f280-c8f7-11ea-8ce5-d270fae19aa1.png)
- Extra quoting in toc.
