### ISSUE TITLE
Efficiency problems after using a full mustache template

### ISSUE THREAD

**Issue by antoniogamiz** [Raku/Documentable#117]
After creating [the default template](https://github.com/Raku/Documentable/blob/develop/resources/template/main.mustache), generation time has increased up to 30 minutes, which is a big problem.  I have come up with the following solution:

- Use Template::Mustache cache capabilities (done in https://github.com/Raku/Pod-To-HTML/pull/77)
- Prepolute menus and submenus in Documentable::To::HTML::Wrapper.

After measuring (approximately) the generation times, we get:
| Change                      | Time|
|----------------------------------|-----------------------------|
| No changes                       | ~ 1500 seconds (25 minutes) |
| (sub)menu pre-population          | ~ 1000 seconds (16 minutes) |
| pre-population + template caching | ~ 500 seconds (8-9 minutes) |

* plus around 3 minutes to create the pod cache.

**Comment by antoniogamiz** [comment]
After the last commit I have realized:

- some tests are missing from Documentable::To::HTML::Wrapper.
- Prepopulation is not supported in Mustache (at the moment, discussion: https://github.com/softmoth/raku-Template-Mustache/issues/36)

**Comment by JJ** [comment]
We can also try and use a different templating system, like
Template::Classic.

**Comment by antoniogamiz** [comment]
In Pod::To::HTML too?

**Comment by JJ** [comment]
We should detach this from Pod::To::HTML, maybe.

**Comment by antoniogamiz** [comment]
I have used Template::Classic here: https://github.com/Raku/Documentable/tree/feat/use-template-classic. Results:

~~~
Generating source files 👇 ...
[=======================================================================]100.00%
Generate source files has taken 228.8313913 seconds 
Generating Kind::Syntax files 👇 ...
[=======================================================================]100.00%
Generating Kind::Routine files 👇 ...
[=======================================================================]100.00%
Generating per kind files has taken 180.3566868 seconds 
Generating indexes...
Generating index files has taken 10.72521574 seconds 
Writing search file...
Generating entries
Writing all generated files 🙌 ...
[#######################################################################]100.00%
Writing generated files has taken 0.8260129 seconds 
Whole process has taken 429.9028253 seconds
~~~

**Comment by JJ** [comment]
It's a bit less than even pre-population + template caching, correct?

**Comment by vrurg** [comment]
I noticed `Template::Mustache` and performance mentioned under the same context and perhaps can give a useful tip. I don't know where exactly the performance suffers the most in this case, but the latest module implementation supports `.hyper/.race` on `rows`:

```raku
%data<rows> = (gather { ...; take { :$record } }).hyper;
```

I use it this way in `Vikna` in a tool which produces HTML out of a sqlite.

**Comment by antoniogamiz** [comment]
> It's a bit less than even pre-population + template caching, correct?

Both `develop` and `feat/use-template-classic` implements pre-popultation + template caching. In the first one, pre-population is made by `Template::Mustache` (and by that reason, it does not work, see https://github.com/softmoth/raku-Template-Mustache/issues/36). In the other, it's made by `Template::Classic`.

In that particular case, it seems faster, but it should take the same amount of time (approx) because once templates are pre-populated, all the work is made by `Pod::To::HTML`.

**Comment by antoniogamiz** [comment]
> I noticed `Template::Mustache` and performance mentioned under the same context and perhaps can give a useful tip. I don't know where exactly the performance suffers the most in this case, but the latest module implementation supports `.hyper/.race` on `rows`:
> 
> ```perl6fe
> %data<rows> = (gather { ...; take { :$record } }).hyper;
> ```
> 
> I use it this way in `Vikna` in a tool which produces HTML out of a sqlite.

I tried to use parallelism to generate the HTML pages but the problem is that `Template::Mustache` is used inside `Pod::To::HTML`, which [does not support parallelism](https://github.com/Raku/Pod-To-HTML/issues/63) <sup>1</sup>.

<sup>1</sup> As a curiosity, today is the anniversary of that issue.

**Comment by antoniogamiz** [comment]
> I noticed `Template::Mustache` and performance mentioned under the same context and perhaps can give a useful tip. I don't know where exactly the performance suffers the most in this case, but the latest module implementation supports `.hyper/.race` on `rows`:
> 
> ```perl6fe
> %data<rows> = (gather { ...; take { :$record } }).hyper;
> ```
> 
> I use it this way in `Vikna` in a tool which produces HTML out of a sqlite.

I have tried once again, just in case, but it's still failing:
~~~raku
use Pod::Load;
use Pod::To::HTML;

my $pod = load("Endian.pod6")[0];

my @works = [];
for 1..255 { @works.push: $pod }

@works.race.map({
    render($pod)
})
~~~
