### ISSUE TITLE
Templates directory still called `template` (singular) in downloaded assets

### ISSUE THREAD

**Issue by paultcochrane** [Raku/Documentable#120]
In a clean checkout of Documentable project, the test `t/101-cli.t` fails since the `templates` directory isn't created.  The test output is:

```
$ raku -Ilib t/101-cli.t
    ok 1 - show help message
    1..1
ok 1 - no arguments provided
Setting up the directory...
[WARNING] template/main.mustache will be overriden by this operation
[WARNING] template/search_template.js will be overriden by this operation
[WARNING] template/tg-fragment.html will be overriden by this operation
[WARNING] type-graph.txt will be overriden by this operation
Copying files...
Done.
    ok 1 - Setup lives
    ok 2 - assets directory created
    not ok 3 - templates directory created
    # Failed test 'templates directory created'
    # at t/101-cli.t line 16
```

Looking at the commit history, one sees that this used to be called just `template` (singular rather than plural).  A `git bisect` narrowed the problem down to commit 44e524d20e6a2ad2270b21851b71de51997e30b2, which updated the tests to use the plural form.  My guess is that the `documentable-assets` need to be updated to use `templates` rather than `template`.  One thing that confused me was that the Travis tests seem to be passing from `master`, however, when I tried running the tests on Travis by pushing to my own fork, I saw exactly the same test error.

**To Reproduce**

Check out a fresh copy of Documentable, install the dependencies and then run the failing test script.
```
$ git clone git@github.com:Raku/Documentable.git
$ zef install .
$ raku -Ilib t/101-cli.t
```

** Expected behaviour**

I expected the test to pass and noticed this issue while trying to build the Raku documentation: installation of the Documentable dependency failed due to the failing test.

**Desktop (please complete the following information):**
 - OS: Debian Linux
 - Version: buster

**Comment by antoniogamiz** [comment]
Oh sorry for that. It has to be `template`. I will change that ASAP (later today). Right now I use the same assets file for all versions of Documentable, which is LTA. Sorry for the trouble.

**Comment by paultcochrane** [comment]
Hey no problems!  I'll submit a PR to fix the issue.

**Comment by paultcochrane** [comment]
> Oh sorry for that. It has to be `template`. I will change that ASAP (later today). Right now I use the same assets file for all versions of Documentable, which is LTA. Sorry for the trouble.

Just wondering: how does one build and/or update the assets file if need be?  I thought it might be a good idea to document this and hence would like to provide a patch to the README for that.

**Comment by paultcochrane** [comment]
I can verify that the test failures I was seeing have been fixed, therefore this issue can be closed.
