### ISSUE TITLE
Does not test clean on Rakudo HEAD

### ISSUE THREAD

**Issue by lizmat** [Raku/Documentable#145]
$ raku -v
    Welcome to Rakudo(tm) v2020.10-130-g78b03b626.
    Implementing the Raku(tm) programming language v6.d.
    Built on MoarVM version 2020.10-31-gb13f6a24c.

    Documentable $ prove -e 'raku -Ilib' t
    t/000-meta-test.t ............ ok   
    t/001-load.t ................. ok    
    t/100-utils.t ................ ok   
    t/101-cli.t .................. 1/? [WARNING] assets/js/jquery-3.1.1.min.js will be overriden by this operation
    [WARNING] assets/js/jquery-ui.min.js will be overriden by this operation
    [WARNING] assets/js/jquery.tablesorter.js will be overriden by this operation
    [WARNING] assets/js/main.js will be overriden by this operation
    [WARNING] assets/sass/_highlights.scss will be overriden by this operation
    [WARNING] assets/sass/_jquery-ui.scss will be overriden by this operation
    [WARNING] assets/sass/style.scss will be overriden by this operation
    t/101-cli.t .................. 2/?     # Failed test 'Lives'
        # at t/101-cli.t line 31
        # Cannot resolve caller render(Pod::Block::Named:D, :podPath(Str), :editable(Str), :url(Sub+{Callable[Mu]}), :main-template-path(Str), :editURL(Str)); none of these signatures match:
        #     (IO::Path $file, |c)
        #     (Str $string, |c)
        # Failed test 'Lives'
        # at t/101-cli.t line 35
        # Cannot resolve caller render(Pod::Block::Named:D, :url(Sub+{Callable[Mu]}), :podPath(Str), :main-template-path(Str), :editURL(Str), :editable(Str)); none of these signatures match:
        #     (IO::Path $file, |c)
        #     (Str $string, |c)
    t/101-cli.t .................. Dubious, test returned 2 (wstat 512, 0x200)
    All 2 subtests passed 
    t/102-update.t ............... Cannot resolve caller render(Pod::Block::Named:D, :podPath(Str), :editURL(Str), :main-template-path(Str), :editable(Str), :url(Sub+{Callable[Mu]})); none of these signatures match:
        (IO::Path $file, |c)
        (Str $string, |c)
      in method render at /Users/liz/Github/Documentable/lib/Documentable/To/HTML/Wrapper.pm6 (Documentable::To::HTML::Wrapper) line 109
      in method generate-home-page at /Users/liz/Github/Documentable/lib/Documentable/DocPage/Factory.pm6 (Documentable::DocPage::Factory) line 33
      in sub MAIN at /Users/liz/Github/Documentable/lib/Documentable/CLI.pm6 (Documentable::CLI) line 200
      in block <unit> at t/102-update.t line 12

    t/102-update.t ............... Dubious, test returned 1 (wstat 256, 0x100)
    No subtests run 
    t/102-update_1.t ............. No subtests run 
    t/103-highlight.t ............ ok   
    t/104-update-issue-16-47.t ...     # Failed test 'Lives with a new cache'
        # at t/104-update-issue-16-47.t line 9
        # Cannot resolve caller render(Pod::Block::Named:D, :url(Sub+{Callable[Mu]}), :main-template-path(Str), :editURL(Str), :editable(Str), :podPath(Str)); none of these signatures match:
        #     (IO::Path $file, |c)
        #     (Str $string, |c)
        # Failed test 'Lives when a new file is added'
        # at t/104-update-issue-16-47.t line 15
        # Cannot resolve caller render(Pod::Block::Named:D, :podPath(Str), :editURL(Str), :url(Sub+{Callable[Mu]}), :editable(Str), :main-template-path(Str)); none of these signatures match:
        #     (IO::Path $file, |c)
        #     (Str $string, |c)
        # You failed 2 tests of 2
    t/104-update-issue-16-47.t ... 1/? # Failed test 'New file added'
    # at t/104-update-issue-16-47.t line 6
        # Failed test 'Lives when a file is deleted'
        # at t/104-update-issue-16-47.t line 25
        # Cannot resolve caller render(Pod::Block::Named:D, :url(Sub+{Callable[Mu]}), :editURL(Str), :editable(Str), :podPath(Str), :main-template-path(Str)); none of these signatures match:
        #     (IO::Path $file, |c)
        #     (Str $string, |c)
        # You failed 1 test of 1
    t/104-update-issue-16-47.t ... 2/? # Failed test 'New file added'
    # at t/104-update-issue-16-47.t line 21
    # You failed 2 tests of 2
    t/104-update-issue-16-47.t ... Dubious, test returned 2 (wstat 512, 0x200)
    Failed 2/2 subtests 
    t/200-documentable.t ......... ok   
    t/201-documentable-file.t .... ok   
    t/202-references.t ........... ok   
    t/204-grammar.t .............. ok    
    t/205-url.t .................. ok   
    t/206-documentable-header.t .. ok   
    t/301-registry.t ............. 2/? /Users/liz/Github/Documentable/t/.cache-test-doc directory will be used as a cache. Please do not use any other directory with this name.
    t/301-registry.t ............. ok   
    t/302-process-pod-source.t ... ok   
    t/303-process-pod-dir.t ...... ok   
    t/304-compose-type.t ......... ok   
    t/305-compose.t .............. ok   
    t/305-search.t ............... ok   
    t/306-index.t ................ ok   
    t/400-template.t ............. 8/? Cannot resolve caller render(Array:D, :editURL(Str), :podPath(Str), :main-template-path(Str), :url(Sub+{Callable[Mu]}), :editable(Str)); none of these signatures match:
        (IO::Path $file, |c)
        (Str $string, |c)
      in method render at /Users/liz/Github/Documentable/lib/Documentable/To/HTML/Wrapper.pm6 (Documentable::To::HTML::Wrapper) line 109
      in block <unit> at t/400-template.t line 83

    t/400-template.t ............. Dubious, test returned 1 (wstat 256, 0x100)
    All 8 subtests passed 
    t/401-indexes.t .............. ok   
    t/402-factory.t .............. 1/? Cannot resolve caller render(Pod::Block::Named:D, :url(Sub), :editURL(Str), :main-template-path(Str), :podPath(Str), :editable(Str)); none of these signatures match:
        (IO::Path $file, |c)
        (Str $string, |c)
      in method render at /Users/liz/Github/Documentable/lib/Documentable/To/HTML/Wrapper.pm6 (Documentable::To::HTML::Wrapper) line 109
      in method generate-home-page at /Users/liz/Github/Documentable/lib/Documentable/DocPage/Factory.pm6 (Documentable::DocPage::Factory) line 33
      in block <unit> at t/402-factory.t line 22

    t/402-factory.t .............. Dubious, test returned 1 (wstat 256, 0x100)
    All 1 subtests passed 
    t/403-config.t ............... ok    

    Test Summary Report
    -------------------
    t/101-cli.t                (Wstat: 512 Tests: 2 Failed: 0)
      Non-zero exit status: 2
      Parse errors: No plan found in TAP output
    t/102-update.t             (Wstat: 256 Tests: 0 Failed: 0)
      Non-zero exit status: 1
      Parse errors: No plan found in TAP output
    t/102-update_1.t           (Wstat: 0 Tests: 0 Failed: 0)
      Parse errors: No plan found in TAP output
    t/104-update-issue-16-47.t (Wstat: 512 Tests: 2 Failed: 2)
      Failed tests:  1-2
      Non-zero exit status: 2
    t/400-template.t           (Wstat: 256 Tests: 8 Failed: 0)
      Non-zero exit status: 1
      Parse errors: No plan found in TAP output
    t/402-factory.t            (Wstat: 256 Tests: 1 Failed: 0)
      Non-zero exit status: 1
      Parse errors: No plan found in TAP output
    Files=25, Tests=117, 36 wallclock secs ( 0.07 usr  0.04 sys + 44.88 cusr  5.62 csys = 50.61 CPU)
    Result: FAIL

**Comment by JJ** [comment]
Thanks for the report. I want to say this is probably related to Template::Mustache, but we'll have to check.

**Comment by antoniogamizbadger** [comment]
Could you please try:

1. Delete all versions of `Pod::To::HTML` in your system.
2. Install only the latest one.
3. Try again.

**Comment by antoniogamiz** [comment]
Could you please try:

1. Delete all versions of `Pod::To::HTML` in your system.
2. Install only the latest one.
3. Try again.

**Comment by JJ** [comment]
It's now working in the latest releases, so this probably fixed itself.
