### ISSUE TITLE
Remove redundant `$!filename` from `Documentable::Primary`

### ISSUE THREAD

**Issue by softmoth** [Raku/Documentable#151]
**Is your feature request related to a problem? Please describe.**
Many tests create a `Documentable::Primary` object with a non-matching filename (e.g., `:filename<int>` instead of `operators` in [t/302-process-pod-source.t](https://github.com/Raku/Documentable/blob/c3dbac82a6bd7befd1fc178934c55ec2abdc171b/t/302-process-pod-source.t#L18)). The fact that the object is happily created and used with inconsistent internal data means it's a likely source of bugs.

**Describe the solution you'd like**
Remove the redundant `$!filename` member, and create a `method filename` that uses the `$!source-path` value.

Creating a new `Documentable::Primary` should require only `:source-path` and `:pod`.

An alternative would be to check that `filename` and `source-path` match up, and throw an error if they don't. But I can see no possible benefits to that solution.

**Comment by JJ** [comment]
Sorry for answering to this so late. I'll try to have a look at this.

**Comment by softmoth** [comment]
Thanks, JJ. It's not high priority, I think. It's not as simple as just using the source-path basename, since docs in a subdirectory need their parents (up to `doc/<kind>`) as part of the `filename`.
