### ISSUE TITLE
"make html" broken in raku/doc

### ISSUE THREAD

**Issue by coke** [Raku/Documentable#164]
Trying to use Documentable to build raku/doc's website is throwing an error:

raku/doc#3904

This may be related to #160 in this repo.

**Comment by coke** [comment]
Based on an email conversation with JJ, my current understanding is that Documentable is not intended to be used when building the raku/doc site, so closing this ticket (related item still open, but it's not blocking the raku/doc build).

**Comment by JJ** [comment]
> Based on an email conversation with JJ, my current understanding is that Documentable is not intended to be used when building the raku/doc site, so closing this ticket (related item still open, but it's not blocking the raku/doc build).

What do you mean? Documentable is *precisely* for that. I'm OK with closing, since the fact that `make html` is working or not does not have to do with this repo.

**Comment by coke** [comment]
I'm very confused about  your messaging between here and raku/doc and the email thread, and hope that when we get documentation on how to build the raku/doc site, it will clear things up.
