### ISSUE TITLE
New options to work with the default cache

### ISSUE THREAD

**Issue by tbrowder** [Raku/Documentable#34]
**Is your feature request related to a problem? Please describe.**
A partial build failure was caused by a bad file in the default cache.

**Describe the solution you'd like**
Provide the following commands or something similar for documentable:

1. remove a specific file from the cache
2. clean the cache

Note I solved my immediate problem by manually removing the bad-file's entry in the cache.
However, it looks like maybe there could be some kind of `.cache-ignore` file which would be handy in such circumstances.

**Comment by JJ** [comment]
That's a good one, but something we'll probably have to fix at the cache level. Good catch, and thanks for the report.

**Comment by finanalyst** [comment]
This seems ambiguous. I see two possibilities
a) There is a bad source file, viz. a-file-with-a-compile-error.pod6, in the doc sources
- the aim is to prevent this file from being added to the cache
- a new version of this module, called Pod::From::Cache, traps compile errors, so bad files should not get in.
- a .ignore-cache file would filter the pod-sources being added to the cache
b) A file has got into the cache that should not be extracted.
- a .ignore-cache file would not return the pod content of the source in the cache.
- this can be done in the $cache.pod method. But what would the return value be? Nil or an error thrown?

**Comment by antoniogamiz** [comment]
Done in https://github.com/finanalyst/raku-pod-from-cache.
