### ISSUE TITLE
dir "html" is present in the repo dir after installation but is not needed then

### ISSUE THREAD

**Issue by tbrowder** [Raku/Documentable#45]
Note: My upcoming PR should fix the following minor problem.

**Describe the bug**
Do the following steps in a clean (preferably empty) directory:

~~~
$ clone https://github.com/perl6/Documentable.git
$ cd Documentable
$ ls -CFd *
CHANGELOG.md	  LICENSE     Perl6-Documentable.iml  TODO.md  docs/  resources/
Documentable.iml  META6.json  README.md		      bin/     lib/   t/
~~~

Notice no "html" directory in the top level (but is does exist in the "resources" directory). Then, still in the Documentable directory:

~~~
$ zef install --force-install .
$ ls -CFd *
CHANGELOG.md	  LICENSE     Perl6-Documentable.iml  TODO.md  docs/  lib/	  t/
Documentable.iml  META6.json  README.md		      bin/     html/  resources/
~~~

Notice the "html" directory has been copied from the existing "resources" directory into the top level directory.  Then, still in the same directory run:

~~~
$ documentable setup; documentable clean
$ ls -CFd *
CHANGELOG.md	  LICENSE     Perl6-Documentable.iml  TODO.md  docs/  resources/
Documentable.iml  META6.json  README.md		      bin/     lib/   t/
~~~

Notice the "html" directory is now gone again from the top level.

**Conclusion**
The "html" directory is apparently not needed for the "install" step so it can be eliminated there.

**Comment by JJ** [comment]
Great! Looking forward to it.
