### ISSUE TITLE
Some documents look ugly. And they are not rendered as web pages

### ISSUE THREAD

**Issue by JJ** [Raku/Documentable#51]
This [document](https://github.com/perl6/Documentable/blob/master/docs/Language/configuration-file.pod6) is not rendered properly, so it's unreadable. It would be interesting to generate that in the [gh-pages](https://perl6.github.io/Documentable), which also look positively ugly.

**Comment by antoniogamiz** [comment]
I will add a check to make this change compulsory in every pod file. I have seen some documents in perl6/docs which present this issue too.

**Comment by JJ** [comment]
I don't think it's got to do with the vim line being present...

**Comment by antoniogamiz** [comment]
Mmm, now it's working so... at least it's something. I do not know why GitHub needs that line to detect the pod6 file.

**Comment by antoniogamiz** [comment]
`gh-pages` was fixed too in `v2.0.0`.
