### ISSUE TITLE
It would be nice to read, by default, a config.json in the same directory as the documentation

### ISSUE THREAD

**Issue by JJ** [Raku/Documentable#61]
`config.json` is either read by default from the installation of this module, or needs to be configured via command line. 
It would be nice to have another reasonable default; for instance, to read also from the root directory.

## Suggestion

To change the `zef-path` function so that it returns a file by that name in the current directory too.

**Comment by antoniogamiz** [comment]
zef-path does exactly that. If the file is present in the directory returns that path, if not, returns the "zef path".

**Comment by antoniogamiz** [comment]
By the way, sorry for not solving any issues, I'm very busy with University stuff.

**Comment by JJ** [comment]
It does not seem to:
https://github.com/perl6/Documentable/blob/d66dfcfbe75a7c353cd9ce73bdb5a51da4cfbbb5/lib/Documentable/Utils/IO.pm6#L62-L66
It either reads from "resources" or from the installed resources file. It does not read from the same directory, you would need to create a "resources" directory and put it there.
