### ISSUE TITLE
Either make config required in Documentable::To::HTML::Wrapper or add reasonable defaults

### ISSUE THREAD

**Issue by JJ** [Raku/Documentable#66]
The config file is actually required only in these two lines:

https://github.com/perl6/Documentable/blob/334637080b6488f4972712fb86d3f173d9a5d982/lib/Documentable/To/HTML/Wrapper.pm6#L42-L43

We need either to add reasonable defaults for both, or make it `required`

**Comment by antoniogamiz** [comment]
Required here:
https://github.com/Raku/Documentable/blob/334637080b6488f4972712fb86d3f173d9a5d982/lib/Documentable/Config.pm6#L34-L41

Anyway they have been removed from the wrapper as attributes.
