### ISSUE TITLE
All filenames with a dot need to add .html at the end

### ISSUE THREAD

**Issue by JJ** [Raku/Documentable#72]
In the original `search.js`, these lines:

```
{ category: "infix", value: "..", url: "/routine/.." }
,
{ category: "Routine", value: "...", url: "/routine/..." }
```

added .html at the end. That URL is not really valid, and leads to unexpected pages.

**Comment by antoniogamiz** [comment]
Mm, `documentable` does not add `.html` to any file. Why `.` and `..` cannot be redirected to `..html` and `...html` as the other pages?
