### ISSUE TITLE
Some web pages in this site do not seem to be rendered

### ISSUE THREAD

**Issue by JJ** [Raku/Documentable#76]
For instance, [this one](https://raku.github.io/language/document-format) is missing.

**Comment by antoniogamiz** [comment]
The correct link is [this one](https://raku.github.io/Documentable/language/document-format) (you need to append the name of the repository) see [url-prefix](https://raku.github.io/Documentable/language/configuration-file#Additional_entries).

Though I have just noticed that there some problems with links generated with that option.

**Comment by JJ** [comment]
I followed that link from the documentation itself. It might not be a
missing page, but a wrong link.

**Comment by antoniogamiz** [comment]
Superseded by https://github.com/Raku/Documentable/issues/78 (because that's what is causing this).
