### ISSUE TITLE
All cache accesses should be done through the Registry

### ISSUE THREAD

**Issue by JJ** [Raku/Documentable#82]
The registry should be the single source of truth. However, in CLI::Update the cache is accessed directly:

https://github.com/Raku/Documentable/blob/master/lib/Documentable/CLI.pm6#L262

This is jumping layer, and is probably NotAGoodIdea(TM)

**Comment by antoniogamiz** [comment]
Done in v2.0.0.

**Comment by JJ** [comment]
Great job, Antonio.
