### ISSUE TITLE
Classes with colons on the middle do not have the GitHub URL right

### ISSUE THREAD

**Issue by JJ** [Raku/Documentable#87]
For [this page](https://docs.raku.org/type/Backtrace::Frame), which has colons in the middle, [the page it points to does not exist](https://github.com/Raku/doc/edit/master/doc/Type/Backtrace::Frame.pod6).

The fact that this has been working for a few months and no one has noticed also says something about the utility of this feature... So alternatively to fixing the bug, we might just eliminate that link to edit the page.

**Comment by antoniogamiz** [comment]
Hum, I suppose we can actually delete it, I have never used it so...

**Comment by JJ** [comment]
Delete what?

**Comment by antoniogamiz** [comment]
The edit button.

**Comment by JJ** [comment]
Ah, right, sorry. I really don't know. We should probably fix it...
