### ISSUE TITLE
Documentable freezes on setup

### ISSUE THREAD

**Issue by vrurg** [Raku/Documentable#90]
Wanted to give a try to Documentable. Unfortunately, it freezes on `documentable setup`.

Here is output of `prove6 -l`:

```
t/000-meta-test.t ............ ok
t/001-load.t ................. ok
t/100-utils.t ................ ok
(warning) html and/or assets and/or templates directories
cannot be found. You can get the defaults by executing:

    documentable setup

Source verified
Got cache at /Users/vrurg/src/Raku/Documentable/t/.cache-test-doc
Caching type/hash
Caching homepage
Caching type/independent-routines
Caching native/int
Caching programs/01-debugging
Caching type/cancellation
Caching type/map
Caching native/multi-class
Caching language/operators
Caching type/any
Caching 404
Caching type/array
Caching type/x/io
Caching programs/02-reading-docs
Caching language/terms
Caching type/associative
Caching type/cool
Cache fully updated
```

Reproducible on on macOS and a Linux Mint VM.

**Comment by JJ** [comment]
Thanks a lot for the report... Can you check if node is available on the path?

**Comment by vrurg** [comment]
Actually, no. On macOS it's v-dispatchers branch. Can't tell you about mint right away as I'm from my iPad now. But should be some April snapshot.

**Comment by vrurg** [comment]
Ok, Mint is _2020.02.1-356-g561076437 built on MoarVM version 2020.02.1-149-gb77aa1622_. macOS is _2020.02.1-379-gca49c153d built on MoarVM version 2020.02.1-162-g3d8ff61e2_.

**Comment by JJ** [comment]
OK, we'll check it out...

**Comment by antoniogamiz** [comment]
Everything should be working now. Though if I run the tests with `prove6 -l`, then `t/400-header-footer.t` fails with:
```bash
Test Summary Report
-------------------
t/400-header-footer.t  (Wstat: 0 Tests: 6 Failed: 0)
  Parse errors: Subtest 6 expected 4 but contains 2 tests
```
I do not know how to fix that, because if you run the test with `raku -Ilib t/400-header-footer.t` it works.

**Comment by vrurg** [comment]
@antoniogamiz I have pulled the latest master and can confirm that tests don't freeze.

With regard to the failing test the problem is line 51 where it is unnecessarily outputs extra HTML code of a footer. Perl's `prove` tolerate this kind of extra output whereas `prove6` apparently doesn't. In either case, it is highly unrecommended to mess up with TAP in a way like this.

Also, two tests result in extra output from (guessing) setting up a new cache. I'd be very preferable to mute them too as potentially it may cause other kind of problems with TAP harenssing.
